"""languages workouts nutrition goal alarm fields recurring overdue

Revision ID: 5f4862e1a8ba
Revises: b1a742b1d01c
Create Date: 2026-09-22 05:35:01.685548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f4862e1a8ba'
down_revision: Union[str, None] = 'b1a742b1d01c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nutrition_goals',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('daily_calorie_goal', sa.Float(), nullable=False),
    sa.Column('protein_goal_grams', sa.Float(), nullable=False),
    sa.Column('fat_goal_grams', sa.Float(), nullable=False),
    sa.Column('carb_goal_grams', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('study_languages',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('flag', sa.String(length=8), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_study_languages_user_id'), 'study_languages', ['user_id'], unique=False)
    op.create_table('workout_plans',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('weekdays', sa.ARRAY(sa.Integer()), nullable=False),
    sa.Column('scheduled_hour', sa.Integer(), nullable=False),
    sa.Column('scheduled_minute', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workout_plans_user_id'), 'workout_plans', ['user_id'], unique=False)
    op.create_table('workout_settings',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('default_rest_seconds', sa.Integer(), nullable=False),
    sa.Column('target_total_minutes', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('workout_completions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['workout_plans.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workout_completions_date'), 'workout_completions', ['date'], unique=False)
    op.create_index(op.f('ix_workout_completions_plan_id'), 'workout_completions', ['plan_id'], unique=False)
    op.create_index(op.f('ix_workout_completions_user_id'), 'workout_completions', ['user_id'], unique=False)
    op.create_table('workout_exercises',
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('reps', sa.Integer(), nullable=False),
    sa.Column('sets', sa.Integer(), nullable=False),
    sa.Column('rest_seconds', sa.Integer(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('video_url', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['workout_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    # NOTE: hand-edited below this point. Autogenerate emitted plain
    # `nullable=False` ADD COLUMNs for columns with no sensible universal
    # default (first_payment_date, words.language_id) — those fail outright
    # against any table that already has rows. It also completely missed
    # that `wake_confirmation_mode` gained three new enum values (Postgres
    # enums require an explicit ALTER TYPE, which Alembic's autogenerate
    # does not detect). Fixed here with a proper add-nullable -> backfill
    # -> set-not-null sequence, and explicit enum value additions.

    # New wake_confirmation_mode values ('puzzle' stays in the DB enum
    # harmlessly — the app just stopped writing that value).
    for value in ('mathProblem', 'vocabGeneral', 'vocabLanguage'):
        op.execute(f"ALTER TYPE wake_confirmation_mode ADD VALUE IF NOT EXISTS '{value}'")

    # recurring_expenses.first_payment_date — backfill existing rows to
    # today's date (the closest honest default: we don't know when an
    # already-existing recurring expense actually started).
    op.add_column('recurring_expenses', sa.Column('first_payment_date', sa.Date(), nullable=True))
    op.execute("UPDATE recurring_expenses SET first_payment_date = CURRENT_DATE WHERE first_payment_date IS NULL")
    op.alter_column('recurring_expenses', 'first_payment_date', nullable=False)

    op.add_column('tasks', sa.Column('alarm_language_id', sa.UUID(), nullable=True))
    # Alembic doesn't auto-CREATE a new enum TYPE for add_column() on an
    # existing table (only for whole-table creation) — without this, the
    # next line fails with "type alarm_sound does not exist".
    alarm_sound_enum = sa.Enum('classic', 'gentle', 'urgent', 'custom', name='alarm_sound')
    alarm_sound_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('tasks', sa.Column('alarm_sound', alarm_sound_enum, nullable=False, server_default='classic'))
    op.alter_column('tasks', 'alarm_sound', server_default=None)
    op.add_column('tasks', sa.Column('custom_song_title', sa.String(length=300), nullable=True))
    op.add_column('tasks', sa.Column('custom_song_persistent_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tasks', 'study_languages', ['alarm_language_id'], ['id'])

    # words: language_code (free-text) -> language_id (FK to a real
    # StudyLanguage row). Existing words can't be auto-assigned to a
    # language a user hasn't created in the new system, so we synthesize
    # one StudyLanguage per distinct (user_id, old language_code) and point
    # existing words at it — nothing is silently dropped.
    op.add_column('words', sa.Column('language_id', sa.UUID(), nullable=True))
    op.add_column('words', sa.Column('miss_count', sa.Integer(), nullable=False, server_default='0'))
    op.alter_column('words', 'miss_count', server_default=None)
    op.add_column('words', sa.Column('needs_review', sa.Boolean(), nullable=False, server_default='false'))
    op.alter_column('words', 'needs_review', server_default=None)

    op.execute("""
        INSERT INTO study_languages (id, user_id, name, flag, created_at)
        SELECT gen_random_uuid(), sub.user_id, sub.language_code, '🌐', now()
        FROM (SELECT DISTINCT user_id, language_code FROM words) AS sub
        ON CONFLICT DO NOTHING
    """)
    op.execute("""
        UPDATE words w
        SET language_id = sl.id
        FROM study_languages sl
        WHERE sl.user_id = w.user_id AND sl.name = w.language_code AND w.language_id IS NULL
    """)
    op.alter_column('words', 'language_id', nullable=False)

    op.create_index(op.f('ix_words_created_at'), 'words', ['created_at'], unique=False)
    op.create_index(op.f('ix_words_language_id'), 'words', ['language_id'], unique=False)
    op.create_foreign_key(None, 'words', 'study_languages', ['language_id'], ['id'])
    op.drop_column('words', 'language_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('words', sa.Column('language_code', sa.VARCHAR(length=8), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'words', type_='foreignkey')
    op.drop_index(op.f('ix_words_language_id'), table_name='words')
    op.drop_index(op.f('ix_words_created_at'), table_name='words')
    op.drop_column('words', 'needs_review')
    op.drop_column('words', 'miss_count')
    op.drop_column('words', 'language_id')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'custom_song_persistent_id')
    op.drop_column('tasks', 'custom_song_title')
    op.drop_column('tasks', 'alarm_sound')
    op.drop_column('tasks', 'alarm_language_id')
    op.drop_column('recurring_expenses', 'first_payment_date')
    op.drop_table('workout_exercises')
    op.drop_index(op.f('ix_workout_completions_user_id'), table_name='workout_completions')
    op.drop_index(op.f('ix_workout_completions_plan_id'), table_name='workout_completions')
    op.drop_index(op.f('ix_workout_completions_date'), table_name='workout_completions')
    op.drop_table('workout_completions')
    op.drop_table('workout_settings')
    op.drop_index(op.f('ix_workout_plans_user_id'), table_name='workout_plans')
    op.drop_table('workout_plans')
    op.drop_index(op.f('ix_study_languages_user_id'), table_name='study_languages')
    op.drop_table('study_languages')
    op.drop_table('nutrition_goals')
    # ### end Alembic commands ###
