"""initial schema

Revision ID: b1a742b1d01c
Revises: 
Create Date: 2026-09-01 04:15:33.808540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1a742b1d01c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('total_xp', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('achievements',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('icon_name', sa.String(length=80), nullable=False),
    sa.Column('achieved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('progress_current', sa.Integer(), nullable=False),
    sa.Column('progress_target', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_achievements_user_id'), 'achievements', ['user_id'], unique=False)
    op.create_table('books',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('author', sa.String(length=200), nullable=False),
    sa.Column('cover_image_url', sa.String(length=500), nullable=True),
    sa.Column('total_pages', sa.Integer(), nullable=False),
    sa.Column('current_page', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('wantToRead', 'reading', 'finished', 'onHold', name='book_status'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('would_recommend', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_books_user_id'), 'books', ['user_id'], unique=False)
    op.create_table('credits',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('remaining_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('monthly_payment', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('interest_rate', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('payment_day', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_closed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credits_user_id'), 'credits', ['user_id'], unique=False)
    op.create_table('daily_summaries',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('tasks_completed', sa.Integer(), nullable=False),
    sa.Column('tasks_total', sa.Integer(), nullable=False),
    sa.Column('water_ml', sa.Integer(), nullable=False),
    sa.Column('water_goal_ml', sa.Integer(), nullable=False),
    sa.Column('calories_consumed', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('calories_goal', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('workout_done', sa.Boolean(), nullable=False),
    sa.Column('reading_minutes', sa.Integer(), nullable=False),
    sa.Column('income_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('expense_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('saved_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('xp_earned', sa.Integer(), nullable=False),
    sa.Column('mood_note', sa.String(length=1000), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_summaries_date'), 'daily_summaries', ['date'], unique=False)
    op.create_index(op.f('ix_daily_summaries_user_id'), 'daily_summaries', ['user_id'], unique=False)
    op.create_table('food_items',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('grams', sa.Float(), nullable=False),
    sa.Column('calories', sa.Float(), nullable=False),
    sa.Column('proteins', sa.Float(), nullable=False),
    sa.Column('fats', sa.Float(), nullable=False),
    sa.Column('carbs', sa.Float(), nullable=False),
    sa.Column('meal_type', sa.Enum('breakfast', 'lunch', 'dinner', 'snack', name='meal_type'), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_food_items_date'), 'food_items', ['date'], unique=False)
    op.create_index(op.f('ix_food_items_user_id'), 'food_items', ['user_id'], unique=False)
    op.create_table('habits',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('icon_name', sa.String(length=80), nullable=False),
    sa.Column('color_hex', sa.String(length=8), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('current_streak', sa.Integer(), nullable=False),
    sa.Column('longest_streak', sa.Integer(), nullable=False),
    sa.Column('freezes_available', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_habits_user_id'), 'habits', ['user_id'], unique=False)
    op.create_table('learning_goals',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('icon_name', sa.String(length=80), nullable=False),
    sa.Column('kind', sa.Enum('language', 'math', 'course', 'custom', name='learning_goal_kind'), nullable=False),
    sa.Column('target_description', sa.String(length=300), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('current_streak', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_goals_user_id'), 'learning_goals', ['user_id'], unique=False)
    op.create_table('math_exercise_records',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('question_text', sa.String(length=200), nullable=False),
    sa.Column('correct_answer', sa.Float(), nullable=False),
    sa.Column('user_answer', sa.Float(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('operation', sa.Enum('addition', 'subtraction', 'multiplication', 'division', 'percentage', 'power', name='math_operation'), nullable=False),
    sa.Column('difficulty', sa.Enum('easy', 'medium', 'hard', name='math_difficulty'), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_math_exercise_records_date'), 'math_exercise_records', ['date'], unique=False)
    op.create_index(op.f('ix_math_exercise_records_user_id'), 'math_exercise_records', ['user_id'], unique=False)
    op.create_table('recurring_expenses',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('icon_name', sa.String(length=80), nullable=False),
    sa.Column('day_of_month', sa.Integer(), nullable=False),
    sa.Column('period', sa.Enum('monthly', 'weekly', 'yearly', name='recurrence_period'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_confirmed_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recurring_expenses_user_id'), 'recurring_expenses', ['user_id'], unique=False)
    op.create_table('savings_goals',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('target_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('saved_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('icon_name', sa.String(length=80), nullable=False),
    sa.Column('color_hex', sa.String(length=8), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_savings_goals_user_id'), 'savings_goals', ['user_id'], unique=False)
    op.create_table('tasks',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('icon_name', sa.String(length=80), nullable=False),
    sa.Column('scheduled_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_done', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.String(length=2000), nullable=False),
    sa.Column('repeat_rule', sa.Enum('once', 'daily', 'weekdays', 'weekly', 'monthly', name='task_repeat_rule'), nullable=False),
    sa.Column('weekdays', sa.ARRAY(sa.Integer()), nullable=False),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', name='task_priority'), nullable=False),
    sa.Column('category_name', sa.String(length=80), nullable=False),
    sa.Column('reminder_offset_minutes', sa.Integer(), nullable=True),
    sa.Column('is_alarm', sa.Boolean(), nullable=False),
    sa.Column('wake_confirmation_mode', sa.Enum('none', 'tap', 'photo', 'puzzle', name='wake_confirmation_mode'), nullable=False),
    sa.Column('wake_confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_scheduled_date'), 'tasks', ['scheduled_date'], unique=False)
    op.create_index(op.f('ix_tasks_user_id'), 'tasks', ['user_id'], unique=False)
    op.create_table('transaction_categories',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('icon_name', sa.String(length=80), nullable=False),
    sa.Column('color_hex', sa.String(length=8), nullable=False),
    sa.Column('kind', sa.Enum('income', 'expense', 'transfer', name='category_kind'), nullable=False),
    sa.Column('is_custom', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wallets',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('balance', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency_code', sa.String(length=8), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('water_goals',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('daily_goal_ml', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('water_intakes',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('amount_ml', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_water_intakes_date'), 'water_intakes', ['date'], unique=False)
    op.create_index(op.f('ix_water_intakes_user_id'), 'water_intakes', ['user_id'], unique=False)
    op.create_table('water_reminder_settings',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('interval_minutes', sa.Integer(), nullable=False),
    sa.Column('start_hour', sa.Integer(), nullable=False),
    sa.Column('start_minute', sa.Integer(), nullable=False),
    sa.Column('end_hour', sa.Integer(), nullable=False),
    sa.Column('end_minute', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('words',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('term', sa.String(length=200), nullable=False),
    sa.Column('translation', sa.String(length=200), nullable=False),
    sa.Column('language_code', sa.String(length=8), nullable=False),
    sa.Column('is_learned', sa.Boolean(), nullable=False),
    sa.Column('last_reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_words_user_id'), 'words', ['user_id'], unique=False)
    op.create_table('xp_records',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('source', sa.Enum('wakeOnTime', 'workout', 'reading', 'readingPages', 'germanWords', 'math', 'bookFinished', 'task', 'habit', 'water', 'other', name='xp_source'), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('note', sa.String(length=300), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_xp_records_user_id'), 'xp_records', ['user_id'], unique=False)
    op.create_table('book_chapters',
    sa.Column('book_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('page_range_start', sa.Integer(), nullable=False),
    sa.Column('page_range_end', sa.Integer(), nullable=False),
    sa.Column('recap', sa.String(length=2000), nullable=False),
    sa.Column('what_i_learned', sa.String(length=2000), nullable=False),
    sa.Column('key_takeaway', sa.String(length=2000), nullable=False),
    sa.Column('thoughts', sa.String(length=2000), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('book_notes',
    sa.Column('book_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('recap', sa.String(length=2000), nullable=False),
    sa.Column('main_idea', sa.String(length=2000), nullable=False),
    sa.Column('personal_thought', sa.String(length=2000), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('book_summaries',
    sa.Column('book_id', sa.UUID(), nullable=False),
    sa.Column('recap', sa.String(length=2000), nullable=False),
    sa.Column('key_takeaway', sa.String(length=2000), nullable=False),
    sa.Column('what_i_learned', sa.String(length=2000), nullable=False),
    sa.Column('what_i_will_apply', sa.String(length=2000), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('would_recommend', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('book_id')
    )
    op.create_table('credit_payments',
    sa.Column('credit_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['credit_id'], ['credits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('habit_completions',
    sa.Column('habit_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('used_freeze', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['habit_id'], ['habits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_habit_completions_date'), 'habit_completions', ['date'], unique=False)
    op.create_table('learning_sessions',
    sa.Column('goal_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('progress_note', sa.String(length=300), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['goal_id'], ['learning_goals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reading_sessions',
    sa.Column('book_id', sa.UUID(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('start_page', sa.Integer(), nullable=False),
    sa.Column('end_page', sa.Integer(), nullable=False),
    sa.Column('recap', sa.String(length=2000), nullable=False),
    sa.Column('main_idea', sa.String(length=2000), nullable=False),
    sa.Column('personal_thought', sa.String(length=2000), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('savings_transactions',
    sa.Column('goal_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['goal_id'], ['savings_goals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('type', sa.Enum('income', 'expense', 'transfer', name='transaction_type'), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('comment', sa.String(length=500), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('linked_savings_goal_id', sa.UUID(), nullable=True),
    sa.Column('linked_credit_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['transaction_categories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_date'), 'transactions', ['date'], unique=False)
    op.create_index(op.f('ix_transactions_user_id'), 'transactions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_user_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_date'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_table('savings_transactions')
    op.drop_table('reading_sessions')
    op.drop_table('learning_sessions')
    op.drop_index(op.f('ix_habit_completions_date'), table_name='habit_completions')
    op.drop_table('habit_completions')
    op.drop_table('credit_payments')
    op.drop_table('book_summaries')
    op.drop_table('book_notes')
    op.drop_table('book_chapters')
    op.drop_index(op.f('ix_xp_records_user_id'), table_name='xp_records')
    op.drop_table('xp_records')
    op.drop_index(op.f('ix_words_user_id'), table_name='words')
    op.drop_table('words')
    op.drop_table('water_reminder_settings')
    op.drop_index(op.f('ix_water_intakes_user_id'), table_name='water_intakes')
    op.drop_index(op.f('ix_water_intakes_date'), table_name='water_intakes')
    op.drop_table('water_intakes')
    op.drop_table('water_goals')
    op.drop_table('wallets')
    op.drop_table('transaction_categories')
    op.drop_index(op.f('ix_tasks_user_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_scheduled_date'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_savings_goals_user_id'), table_name='savings_goals')
    op.drop_table('savings_goals')
    op.drop_index(op.f('ix_recurring_expenses_user_id'), table_name='recurring_expenses')
    op.drop_table('recurring_expenses')
    op.drop_index(op.f('ix_math_exercise_records_user_id'), table_name='math_exercise_records')
    op.drop_index(op.f('ix_math_exercise_records_date'), table_name='math_exercise_records')
    op.drop_table('math_exercise_records')
    op.drop_index(op.f('ix_learning_goals_user_id'), table_name='learning_goals')
    op.drop_table('learning_goals')
    op.drop_index(op.f('ix_habits_user_id'), table_name='habits')
    op.drop_table('habits')
    op.drop_index(op.f('ix_food_items_user_id'), table_name='food_items')
    op.drop_index(op.f('ix_food_items_date'), table_name='food_items')
    op.drop_table('food_items')
    op.drop_index(op.f('ix_daily_summaries_user_id'), table_name='daily_summaries')
    op.drop_index(op.f('ix_daily_summaries_date'), table_name='daily_summaries')
    op.drop_table('daily_summaries')
    op.drop_index(op.f('ix_credits_user_id'), table_name='credits')
    op.drop_table('credits')
    op.drop_index(op.f('ix_books_user_id'), table_name='books')
    op.drop_table('books')
    op.drop_index(op.f('ix_achievements_user_id'), table_name='achievements')
    op.drop_table('achievements')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
